services:
  botgodownloader:
    build: .
    container_name: botgodownloader
    restart: unless-stopped
    environment:
      - NEOXR_API_KEY=${NEOXR_API_KEY}
      - TZ=Asia/Jakarta
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    stop_grace_period: 10s
